/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_interface;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ANIK ADRISH MAJHI
 */
public class ChangePin_Page extends javax.swing.JFrame {

    Connection con;
    /**
     * Creates new form Deposite_Page
     */
    public ChangePin_Page() {
        initComponents();
    }
    
    String account;
    public ChangePin_Page(String accountNum) {
        initComponents();
        account = accountNum;
        lbl_balance.setText(account);
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_balance = new javax.swing.JLabel();
        txt_Pin2 = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Pin1 = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_interface/atm icon/png-transparent-white-bank-illustration-online-banking-finance-icon-white-bank-building-building-black-white-cartoon.png"))); // NOI18N
        jLabel1.setText("WELCOME TO ATM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_balance.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_balance.setForeground(new java.awt.Color(255, 255, 255));
        lbl_balance.setText("Your Balance :");
        jPanel2.add(lbl_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 180, 40));

        txt_Pin2.setBackground(new java.awt.Color(0, 102, 102));
        txt_Pin2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Pin2.setForeground(new java.awt.Color(255, 255, 255));
        txt_Pin2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_Pin2.setPhColor(new java.awt.Color(255, 255, 255));
        txt_Pin2.setPlaceholder("Enter Confirm Pin");
        txt_Pin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Pin2ActionPerformed(evt);
            }
        });
        txt_Pin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Pin2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Pin2KeyReleased(evt);
            }
        });
        jPanel2.add(txt_Pin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHANGE PIN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 40));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 130, -1));

        lblError.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 390, 20));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 260, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Pin :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 150, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Account No:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("New Pin :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, 40));

        txt_Pin1.setBackground(new java.awt.Color(0, 102, 102));
        txt_Pin1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Pin1.setForeground(new java.awt.Color(255, 255, 255));
        txt_Pin1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_Pin1.setPhColor(new java.awt.Color(255, 255, 255));
        txt_Pin1.setPlaceholder("Enter New Pin");
        txt_Pin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Pin1ActionPerformed(evt);
            }
        });
        txt_Pin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Pin1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Pin1KeyReleased(evt);
            }
        });
        jPanel2.add(txt_Pin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 600, 430));

        setSize(new java.awt.Dimension(600, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_Pin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Pin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Pin2ActionPerformed

    private void txt_Pin2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Pin2KeyPressed

    }//GEN-LAST:event_txt_Pin2KeyPressed

    private void txt_Pin2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Pin2KeyReleased

    }//GEN-LAST:event_txt_Pin2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(txt_Pin1.getText().isEmpty() || txt_Pin2.getText().equals(0)){
            JOptionPane.showMessageDialog(this, "Enter The Pin");
        } else if(!txt_Pin1.getText().equals(txt_Pin2.getText())){
            JOptionPane.showMessageDialog(this, "Pin should be same");
        }
        else{
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_interface","root","");
            String sql = "update signup set pin=?,confirm_pin=? where account_no=?";
            PreparedStatement stmt = con.prepareStatement(sql);
            
            stmt.setString(1, txt_Pin1.getText());
            stmt.setString(2, txt_Pin2.getText());
            stmt.setString(3, account);
            
            if(stmt.executeUpdate()==1){
                JOptionPane.showMessageDialog(this, "pin updated");
                
                Login_Page home = new Login_Page();
                home.show();
                this.dispose();
                
            }else {
                JOptionPane.showMessageDialog(this, "can't updated");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Home_Page s = new Home_Page(account);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void txt_Pin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Pin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Pin1ActionPerformed

    private void txt_Pin1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Pin1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Pin1KeyPressed

    private void txt_Pin1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Pin1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Pin1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePin_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lbl_balance;
    private app.bolivia.swing.JCTextField txt_Pin1;
    private app.bolivia.swing.JCTextField txt_Pin2;
    // End of variables declaration//GEN-END:variables
}
