/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_interface;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author ANIK ADRISH MAJHI
 */
public class Login_Page extends javax.swing.JFrame {
    
    Connection con;

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
    }

    
    void userVerification(String cardNo,String pin){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_interface","root","");
            String sql = "select * from signup where card_no=? and pin=?";
            PreparedStatement stmt = con.prepareStatement(sql);
            
            stmt.setString(1, cardNo);
            stmt.setString(2, pin);
            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                
                //JOptionPane.showMessageDialog(this, "Login successful");
                
                new Home_Page(rs.getString(1)).setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this, "wrong username or password");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_CardNo = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Pin = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_interface/atm icon/png-transparent-white-bank-illustration-online-banking-finance-icon-white-bank-building-building-black-white-cartoon.png"))); // NOI18N
        jLabel1.setText("WELCOME TO ATM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Card No :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 40));

        txt_CardNo.setBackground(new java.awt.Color(0, 102, 102));
        txt_CardNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_CardNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_CardNo.setPlaceholder("Enter Last 4 Digit of  Card No");
        txt_CardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CardNoActionPerformed(evt);
            }
        });
        txt_CardNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CardNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CardNoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_CardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pin No :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 40));

        txt_Pin.setBackground(new java.awt.Color(0, 102, 102));
        txt_Pin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Pin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_Pin.setPlaceholder("Enter 4 Digit Pin");
        txt_Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PinActionPerformed(evt);
            }
        });
        txt_Pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PinKeyReleased(evt);
            }
        });
        jPanel2.add(txt_Pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 240, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 120, 60));

        lblError.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 390, 20));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Signup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 600, 430));

        setSize(new java.awt.Dimension(600, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_CardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CardNoActionPerformed

    private void txt_CardNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CardNoKeyPressed
       
    }//GEN-LAST:event_txt_CardNoKeyPressed

    private void txt_CardNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CardNoKeyReleased
        
    }//GEN-LAST:event_txt_CardNoKeyReleased

    private void txt_PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PinActionPerformed

    private void txt_PinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PinKeyPressed
        
    }//GEN-LAST:event_txt_PinKeyPressed

    private void txt_PinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PinKeyReleased
       
    }//GEN-LAST:event_txt_PinKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cardNo = txt_CardNo.getText();
        String pin = txt_Pin.getText();
        
        if(cardNo.trim().equals("") || pin.trim().equals("")) {
            lblError.setText("please enter Account No  and pin");
        } else {
            userVerification(cardNo,pin);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Signup_Page home = new Signup_Page();
                home.show();
                this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblError;
    private app.bolivia.swing.JCTextField txt_CardNo;
    private app.bolivia.swing.JCTextField txt_Pin;
    // End of variables declaration//GEN-END:variables
}
