/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_interface;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ANIK ADRISH MAJHI
 */
public class Signup_Page extends javax.swing.JFrame {

    Connection con;
    /**
     * Creates new form Signup_Page
     */
    
    String accountNo,cardNo,name,pin,confirmPin,contactNo;
    int balance;
    Date dob;
    public Signup_Page() {
        initComponents();
    }
    
    boolean Validation() {
        
        accountNo = txt_AccountNo.getText();
        cardNo = txt_CardNo.getText();
        name = txt_Name.getText();
        pin = txt_Pin.getText();
        confirmPin = txt_ConfirmPin.getText();
        contactNo = txt_PhoneNo.getText();
        dob = txt_dob.getDate();
        
        if(accountNo.equals("")){
            JOptionPane.showMessageDialog(this, "please enter account number");
            return false;
        }
        
        if(cardNo.equals("")){
            JOptionPane.showMessageDialog(this, "please enter card number");
            return false;
        }
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "please enter account holder name");
            return false;
        }
        
        if(pin.equals("")){
            JOptionPane.showMessageDialog(this, "please enter 4 digit pin");
            return false;
        }
        
        if(confirmPin.equals("")){
            JOptionPane.showMessageDialog(this, "enter confirm pin");
            return false;
        }
        
        if(dob.equals(null)){
            JOptionPane.showMessageDialog(this, "please enter date of birth");
            return false;
        }
        
        if(!pin.equals(confirmPin)){
            JOptionPane.showMessageDialog(this, "password not matched");
            return false;
        }   
        if(contactNo.equals("")){
            JOptionPane.showMessageDialog(this, "enter contact no");
            return false;
        }
        return true;
    }
    
    public void checkAccount(){
        accountNo = txt_AccountNo.getText();
        if(accountNo.length()!=11){
            lbl_account.setText("*");
        }
        else {
            lbl_account.setText("");
        }
    }
    
    public void checkCard(){
        cardNo = txt_CardNo.getText();
        if(cardNo.length()!=4){
            lbl_card.setText("*");
        }
        else {
            lbl_card.setText("");
        }
    }

    public void checkPin(){
        pin = txt_Pin.getText();
        if(pin.length()!=4){
            lbl_pin.setText("*");
        }
        else {
            lbl_pin.setText("");
        }
    }
    
    public void checkConfirmPin(){
        confirmPin = txt_ConfirmPin.getText();
        if(pin.length()!=4){
            lbl_confirmPin.setText("*");
        }
        else {
            lbl_confirmPin.setText("");
        }
    }
    
    public void checkContactNo(){
        contactNo = txt_PhoneNo.getText();
        if(contactNo.length() != 10){
            lbl_contact.setText("*");
        }
        else {
            lbl_contact.setText("");
        }
    }
    
    void insertDetails(){
        SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
        String myDob = format.format(dob);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_interface", "root", "");
            String sql = "insert into signup values(?,?,?,?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, accountNo);
            stmt.setString(2, cardNo);
            stmt.setString(3, name);
            stmt.setString(4, pin);
            stmt.setString(5, confirmPin);
            stmt.setString(6, myDob);
            stmt.setString(7, contactNo);
            stmt.setInt(8, balance);

            int i = stmt.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(this, "Signup Successful");
            } else {
                JOptionPane.showMessageDialog(this, "Record not inserted");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_AccountNo = new app.bolivia.swing.JCTextField();
        txt_CardNo = new app.bolivia.swing.JCTextField();
        txt_Name = new app.bolivia.swing.JCTextField();
        txt_PhoneNo = new app.bolivia.swing.JCTextField();
        txt_dob = new com.toedter.calendar.JDateChooser();
        txt_Pin = new app.bolivia.swing.JCTextField();
        txt_ConfirmPin = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        lbl_confirmPin = new javax.swing.JLabel();
        lbl_pin = new javax.swing.JLabel();
        lbl_account = new javax.swing.JLabel();
        lbl_card = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_interface/atm icon/png-transparent-white-bank-illustration-online-banking-finance-icon-white-bank-building-building-black-white-cartoon.png"))); // NOI18N
        jLabel1.setText("WELCOME TO ATM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account Holder Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account No :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone No :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 190, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ATM Card No :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pin No :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm Pin :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("D.O.B :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 190, 40));

        txt_AccountNo.setBackground(new java.awt.Color(0, 102, 102));
        txt_AccountNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_AccountNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_AccountNo.setPlaceholder("Enter 11 Digit Account No");
        txt_AccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AccountNoActionPerformed(evt);
            }
        });
        txt_AccountNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_AccountNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_AccountNoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_AccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 240, -1));

        txt_CardNo.setBackground(new java.awt.Color(0, 102, 102));
        txt_CardNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_CardNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_CardNo.setPlaceholder("Enter Last 4 Digit Card No");
        txt_CardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CardNoActionPerformed(evt);
            }
        });
        txt_CardNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CardNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CardNoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_CardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 240, -1));

        txt_Name.setBackground(new java.awt.Color(0, 102, 102));
        txt_Name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_Name.setPlaceholder("Enter Account Holder Name");
        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 240, -1));

        txt_PhoneNo.setBackground(new java.awt.Color(0, 102, 102));
        txt_PhoneNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_PhoneNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_PhoneNo.setPlaceholder("Enter Phone No");
        txt_PhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhoneNoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_PhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 240, -1));

        txt_dob.setBackground(new java.awt.Color(0, 102, 102));
        txt_dob.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_dob.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jPanel2.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 240, 40));

        txt_Pin.setBackground(new java.awt.Color(0, 102, 102));
        txt_Pin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Pin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_Pin.setPlaceholder("Enter 4 Digit Pin");
        txt_Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PinActionPerformed(evt);
            }
        });
        txt_Pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PinKeyReleased(evt);
            }
        });
        jPanel2.add(txt_Pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 240, -1));

        txt_ConfirmPin.setBackground(new java.awt.Color(0, 102, 102));
        txt_ConfirmPin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_ConfirmPin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        txt_ConfirmPin.setPlaceholder("Confirm 4 Digit Pin");
        txt_ConfirmPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ConfirmPinActionPerformed(evt);
            }
        });
        txt_ConfirmPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ConfirmPinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ConfirmPinKeyReleased(evt);
            }
        });
        jPanel2.add(txt_ConfirmPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 240, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 25)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, 60));

        lbl_confirmPin.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbl_confirmPin.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lbl_confirmPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 30, 20));

        lbl_pin.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbl_pin.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lbl_pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 30, 20));

        lbl_account.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbl_account.setForeground(new java.awt.Color(204, 0, 51));
        jPanel2.add(lbl_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 40, 20));

        lbl_card.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbl_card.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lbl_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 40, 20));

        lbl_contact.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbl_contact.setForeground(new java.awt.Color(204, 0, 51));
        jPanel2.add(lbl_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 30, 20));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 120, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 600, 670));

        setSize(new java.awt.Dimension(600, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_AccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AccountNoActionPerformed

    private void txt_CardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CardNoActionPerformed

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void txt_PhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhoneNoActionPerformed

    private void txt_PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PinActionPerformed

    private void txt_ConfirmPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ConfirmPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ConfirmPinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Validation()){
            insertDetails(); 
            
            Login_Page s = new Login_Page();
            s.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_AccountNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AccountNoKeyPressed
        checkAccount();
    }//GEN-LAST:event_txt_AccountNoKeyPressed

    private void txt_AccountNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AccountNoKeyReleased
        checkAccount();
    }//GEN-LAST:event_txt_AccountNoKeyReleased

    private void txt_CardNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CardNoKeyPressed
        checkCard();
    }//GEN-LAST:event_txt_CardNoKeyPressed

    private void txt_CardNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CardNoKeyReleased
       checkCard();
    }//GEN-LAST:event_txt_CardNoKeyReleased

    private void txt_PinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PinKeyPressed
        checkPin();
    }//GEN-LAST:event_txt_PinKeyPressed

    private void txt_PinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PinKeyReleased
        checkPin();
    }//GEN-LAST:event_txt_PinKeyReleased

    private void txt_ConfirmPinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ConfirmPinKeyPressed
        checkConfirmPin();
    }//GEN-LAST:event_txt_ConfirmPinKeyPressed

    private void txt_ConfirmPinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ConfirmPinKeyReleased
        checkConfirmPin();
    }//GEN-LAST:event_txt_ConfirmPinKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login_Page s = new Login_Page();
            s.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_card;
    private javax.swing.JLabel lbl_confirmPin;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_pin;
    private app.bolivia.swing.JCTextField txt_AccountNo;
    private app.bolivia.swing.JCTextField txt_CardNo;
    private app.bolivia.swing.JCTextField txt_ConfirmPin;
    private app.bolivia.swing.JCTextField txt_Name;
    private app.bolivia.swing.JCTextField txt_PhoneNo;
    private app.bolivia.swing.JCTextField txt_Pin;
    private com.toedter.calendar.JDateChooser txt_dob;
    // End of variables declaration//GEN-END:variables
}
